#!/usr/bin/env bash
#This script configures a machine with respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html