#!/usr/bin/env bash
#This script configures a machine with respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a      rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sudo sed -i "s/server_name _;/server_name alejandroarbelaezdev.tech;/" /etc/nginx/sites-available/defau$
sudo service nginx start
