#!/usr/bin/env bash
#This script configures a machine with respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx start

