#!/usr/bin/env bash
#This script configures a machine with respect above requirements
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name/a\\n\terror_page 404 \/custom_404.html;\n\tlocation \/custom_404.html \{\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\}\n' /etc/nginx/sites-available/default
sudo service nginx restart