#!/usr/bin/env bash
#This script configures a machine with respect above requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen 80 default_server;/a\\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default
sudo service nginx restart
