#!/usr/bin/env bash
#This script configures a machine with respect above requirements
apt-get update && apt-get upgrade -y
apt-get install haproxy -y
echo "frontend http_front
        bind *:80
        stats uri /haproxy?stats
        default_backend http_back
" >> /etc/haproxy/haproxy.cfg
echo "backend http_back
        balance roundrobin
        server 1158-web-01 34.74.97.231:80 check
        server 1158-web-02 35.227.41.101:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
