#!/usr/bin/env bash
#This script generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases --single-transaction --user=root --password=$1 > backup.sql
d=`date +%d-%m-%Y`
tar -czvf $d.tar.gz backup.sql