#!/usr/bin/env bash
# This script with an infinity loop
echo $$ > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT 

num=0
while [ "$num" -le 0 ]
do
  echo To infinity and beyond
  sleep 2
done
