#!/usr/bin/env bash
# This script is displaying the time 12 hours and 59 minutes
h=0
m=1
while [ "$h" -le 12 ] && [ "$m" -le 59 ]
do
  if [ "$m" == 1 ]
  then
    echo "Hour: $h"
  fi
  echo "$m"
  m=$(( m + 1 ))
  if [ "$m" == 59 ]
  then
    echo "$m"
    h=$(( h + 1 ))
    m=1
  fi
done
